# Session-signing key for the management UI's admin cookie (Stage 4). Generated by Terraform and
# stored in Secret Manager; mounted into the api service as the SESSION_SECRET env var.
# (Per-account OAuth tokens and the Web client config are written to Secret Manager at runtime by
# the app / helper, not here.)
resource "random_password" "session" {
  length  = 48
  special = false
}

resource "google_secret_manager_secret" "session" {
  project   = var.project_id
  secret_id = "session-secret"

  replication {
    auto {}
  }

  depends_on = [google_project_service.enabled]
}

resource "google_secret_manager_secret_version" "session" {
  secret      = google_secret_manager_secret.session.id
  secret_data = random_password.session.result
}
